"""Falstad circuit simulator importer

Imports data generated by the "Data Export" objects.
The header must be in "# time step <val> sec" format

Returns a pandas.DataFrame with 'time' and 'voltage'.

See http://falstad.com/circuit/
    Draw -> Outputs and Labels -> Add Data Export
"""
import pandas

TIME_COL_NAME = 'time'
DATA_COL_NAME = 'voltage'

def read(fn, time_index=False) -> pandas.DataFrame or None:
    """Import data from Falstad "Data Export" object"""
    df = pandas.read_table(fn)
    # Parse file-header
    hdr, val = df.columns[0].split('=', 1)
    hdr = hdr.strip()
    val, unit = val.strip().split(' ', 1)
    if hdr != '# time step' or unit != 'sec':
        return None
    val = float(val)

    # Rename data, add time (index) column
    df.columns = [DATA_COL_NAME]
    df.insert(0, TIME_COL_NAME, df.index * val)

    # Use 'time' as index
    if time_index:
        df = df.set_index(TIME_COL_NAME)
    return df

if __name__ == '__main__':
    import sys
    df = read(sys.argv[1], True)
    if df is None:
        sys.exit(1)
    df.to_csv(sys.stdout.buffer)
